FROM alpine:latest

# 配置国内镜像源
RUN echo "https://mirrors.aliyun.com/alpine/v3.21/main/" > /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/v3.21/community/" >> /etc/apk/repositories

# 安装必要的开发工具和头文件
RUN apk add --no-cache gcc musl-dev

# 复制所有文件到容器中
# COPY hello.c /app/
# COPY in.txt /app/

# 设置工作目录
WORKDIR /app

# sudo docker run --rm a
# sudo docker build --progress=plain --no-cache -t a run-file

