apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms
spec:
  replicas: 3
  selector:
      matchLabels:
        app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000